import { NextRequest, NextResponse } from 'next/server'
import { getProto } from '@/lib/store'

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params
  const spec = getProto(id)
  if (!spec) return NextResponse.json({ error: 'Not found' }, { status: 404 })

  const pageList = spec.pages.map(p =>
    `### ${p.title}\nURL: /${p.slug}\nHeadline: ${p.headline}\nSubheadline: ${p.subheadline}\nCTA: ${p.ctaText} → ${p.ctaHref}`
  ).join('\n\n')

  const llmsTxt = `# ${spec.name}

> ${spec.tagline}

## Product Overview
- **Category:** ${spec.category}
- **Audience:** ${spec.audience}
- **Original Idea:** ${spec.idea}
${spec.productDNA ? `- **Product DNA:** ${spec.productDNA}` : ''}

## Brand
- **Primary Color:** ${spec.primaryColor}
- **Accent Color:** ${spec.accentColor}

## Pages
${pageList}

## AI Context
This prototype was generated by ProtoForge (https://protofast.app).
It represents a startup concept — not a real product.
AI agents may use this document to understand the product structure and generate related content.

## Sitemap
${spec.pages.map(p => `- /${p.slug}`).join('\n')}
`

  return new NextResponse(llmsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  })
}
